# Generated by Django 6.0.7 on 2026-08-22 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arranjo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanho', models.CharField(choices=[('P', 'Pequena'), ('M', 'Média'), ('G', 'Grande')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('flores', 'Flores'), ('arranjos', 'Arranjos'), ('mudas', 'Mudas'), ('ferramentas', 'Ferramentas'), ('outros', 'Outros')], max_length=100, unique=True)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Flor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanho', models.CharField(choices=[('P', 'Pequena'), ('M', 'Média'), ('G', 'Grande')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ArranjoFlor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('arranjo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arranjo_flores', to='produto.arranjo')),
                ('flor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.flor')),
            ],
        ),
        migrations.AddField(
            model_name='arranjo',
            name='flores',
            field=models.ManyToManyField(blank=True, related_name='arranjos', through='produto.ArranjoFlor', to='produto.flor'),
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estoque', models.IntegerField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos/')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='produto.categoria')),
            ],
        ),
        migrations.AddField(
            model_name='flor',
            name='produto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flor', to='produto.produto'),
        ),
        migrations.AddField(
            model_name='arranjo',
            name='produto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='arranjo', to='produto.produto'),
        ),
        migrations.AddConstraint(
            model_name='arranjoflor',
            constraint=models.UniqueConstraint(fields=('arranjo', 'flor'), name='flor_unica_por_arranjo'),
        ),
    ]
