# Generated by Django 6.0.7 on 2026-08-25 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arranjo',
            name='flores',
        ),
        migrations.RemoveField(
            model_name='arranjo',
            name='produto',
        ),
        migrations.RemoveConstraint(
            model_name='arranjoflor',
            name='flor_unica_por_arranjo',
        ),
        migrations.RemoveField(
            model_name='flor',
            name='produto',
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='descricao',
            new_name='descricao_categoria',
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='nome',
            new_name='nome_categoria',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='descricao',
            new_name='descricao_produto',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='nome',
            new_name='nome_produto',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='preco',
            new_name='precoUnitario',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='estoque',
            new_name='quantidadeEstoque',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='arranjoflor',
            name='arranjo',
        ),
        migrations.RemoveField(
            model_name='arranjoflor',
            name='flor',
        ),
        migrations.DeleteModel(
            name='Arranjo',
        ),
        migrations.DeleteModel(
            name='ArranjoFlor',
        ),
        migrations.DeleteModel(
            name='Flor',
        ),
    ]
