# Generated by Django 6.0.2 on 2026-09-28 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_remove_arranjo_flores_remove_arranjo_produto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nome_categoria',
            field=models.CharField(choices=[('Flor', 'Flores'), ('Arranjo', 'Arranjos'), ('Muda', 'Mudas'), ('Ferramenta', 'Ferramentas'), ('Outro', 'Outros')], max_length=100, unique=True),
        ),
    ]
