# Generated by Django 6.1 on 2026-09-29 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_alter_categoria_nome_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nome_categoria',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
