# Generated by Django 6.0.7 on 2026-08-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_itempedido_pedido_produtos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempedido',
            name='id_itemPedido',
        ),
        migrations.AddField(
            model_name='itempedido',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
