# Generated by Django 6.0.2 on 2026-09-15 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0003_remove_itempedido_id_itempedido_itempedido_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itempedido',
            old_name='valorUnit',
            new_name='valorUnitario',
        ),
    ]
