# Generated by Django 6.0.2 on 2026-09-28 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0004_rename_valorunit_itempedido_valorunitario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='valorTotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
