# Generated by Django 6.0.2 on 2026-09-29 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0005_alter_pedido_valortotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='dataHora',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
