# Generated by Django 6.0.2 on 2026-09-29 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0006_alter_pedido_datahora'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='numero_pedido',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
